@startuml

:Main Admin: as Admin
(Use the application) as (Use)


User -> (Start)
User --> (Use)

Admin ---> (Use)

note right of Admin : This is an example.

note right of (Use)
A note can also
be on several lines
end note

note "This note is connected\nto several objects." as N2
(Start) .. N2
N2 .. (Use)


(升职加薪)

(Use) ---> (升职加薪)

footer \n\n\n\n\n<b>https://nogeek.cn</b> <img:https://f.umlcn.com/NoGeekAvatar.png> <b>https://umlcn.com</b>\n



@enduml